site_name: Wiki1
site_author: Wiki2
site_url: https://hulopezm.github.io/wiki
nav:
  - Introduction: "index.md"
  - Databases:
      -Databases: Databases/ddbb.md

theme:
  name: material
  palette:
    primary: "blue grey"
    accent: "light blue"

repo_name: hulopezm/wiki
repo_url: https://hulopezm.github.io/wiki
