site_name: Wikipedia
site_author: hugo
site_url: https://hulopezm.github.io/wiki/

nav:
  - Introduction: "index.md"
  - Databases:
      - Databases: Databases/ddbb.md

theme:
  name: material
  palette:
    primary: "blue grey"
    accent: "light blue"

repo_name: hulopezm/wiki
repo_url: https://github.com/hulopezm/wiki

