site_name: Wiki1
site_author: Wiki2
site_url: https://julopezc-acciona.github.io/wiki
nav:
  - Introduction: 'index.md'

theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'light blue'

repo_name: julopezc-acciona/wiki
repo_url: https://julopezc-acciona.github.io/wiki
